Class {
	#name : #CSNBindModel,
	#superclass : #MooseModel,
	#category : #'Casino-Bind-UIBehavior-Model'
}

{ #category : #accessing }
CSNBindModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'FAST-Java-Model' #'FAST-Core-Model' 'Casino-Model-UI-SubEntities' 'Casino-Model-Layout' 'Casino-Model-CoreWeb' #'Casino-Model' #'Casino-Behavior-Model')
]

{ #category : #meta }
CSNBindModel class >> annotation [
	<FMClass: #CSNBindModel super: #MooseModel>
	<package: #'Casino-Bind-UIBehavior'>
	<generated>
]
