Class {
	#name : #CSNUICWModel,
	#superclass : #MooseModel,
	#category : #'Casino-Model-CoreWeb'
}

{ #category : #accessing }
CSNUICWModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' 'Casino-Model-UI-SubEntities' 'Casino-Model-Layout' #'Casino-Model')
]

{ #category : #meta }
CSNUICWModel class >> annotation [
	<MSEClass: #CSNUICWModel super: #MooseModel>
	<package: #'Casino-Model-CoreWeb'>
	<generated>
]
