Class {
	#name : #BLAbsoluteSize,
	#superclass : #BLSize,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLAbsoluteSize class >> annotation [

	<MSEClass: #AbsoluteSize super: #BLSize>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLAbsoluteSize class >> generatedSlotNames [
	<generated>
	'BLAbsoluteSize class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLAbsoluteSize class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLAbsoluteSize class >> requirements [

	<generated>
	^ {  }
]
