Class {
	#name : #BLAbsolutePosition,
	#superclass : #BLPosition,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLAbsolutePosition class >> annotation [

	<MSEClass: #AbsolutePosition super: #BLPosition>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLAbsolutePosition class >> generatedSlotNames [
	<generated>
	'BLAbsolutePosition class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLAbsolutePosition class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLAbsolutePosition class >> requirements [

	<generated>
	^ {  }
]
