Class {
	#name : #BLAlignement,
	#superclass : #BLPosition,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLAlignement class >> annotation [

	<MSEClass: #Alignement super: #BLPosition>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLAlignement class >> generatedSlotNames [
	<generated>
	'BLAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLAlignement class >> requirements [

	<generated>
	^ {  }
]
