Class {
	#name : #BLCenterAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLCenterAlignement class >> annotation [

	<MSEClass: #CenterAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLCenterAlignement class >> generatedSlotNames [
	<generated>
	'BLCenterAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLCenterAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLCenterAlignement class >> requirements [

	<generated>
	^ {  }
]
