Class {
	#name : #BLEastAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLEastAlignement class >> annotation [

	<MSEClass: #EastAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLEastAlignement class >> generatedSlotNames [
	<generated>
	'BLEastAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLEastAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLEastAlignement class >> requirements [

	<generated>
	^ {  }
]
