Class {
	#name : #BLNorthWestAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLNorthWestAlignement class >> annotation [

	<MSEClass: #NorthWestAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLNorthWestAlignement class >> generatedSlotNames [
	<generated>
	'BLNorthWestAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLNorthWestAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLNorthWestAlignement class >> requirements [

	<generated>
	^ {  }
]
