Class {
	#name : #BLNorthAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLNorthAlignement class >> annotation [

	<MSEClass: #NorthAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLNorthAlignement class >> generatedSlotNames [
	<generated>
	'BLNorthAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLNorthAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLNorthAlignement class >> requirements [

	<generated>
	^ {  }
]
