Class {
	#name : #BLNorthEastAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLNorthEastAlignement class >> annotation [

	<MSEClass: #NorthEastAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLNorthEastAlignement class >> generatedSlotNames [
	<generated>
	'BLNorthEastAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLNorthEastAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLNorthEastAlignement class >> requirements [

	<generated>
	^ {  }
]
