Class {
	#name : #BLRelativePosition,
	#superclass : #BLPosition,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLRelativePosition class >> annotation [

	<MSEClass: #RelativePosition super: #BLPosition>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLRelativePosition class >> generatedSlotNames [
	<generated>
	'BLRelativePosition class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLRelativePosition class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLRelativePosition class >> requirements [

	<generated>
	^ {  }
]
