Class {
	#name : #BLRelativeSize,
	#superclass : #BLSize,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLRelativeSize class >> annotation [

	<MSEClass: #RelativeSize super: #BLSize>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLRelativeSize class >> generatedSlotNames [
	<generated>
	'BLRelativeSize class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLRelativeSize class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLRelativeSize class >> requirements [

	<generated>
	^ {  }
]
