Class {
	#name : #BLSouthAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLSouthAlignement class >> annotation [

	<MSEClass: #SouthAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLSouthAlignement class >> generatedSlotNames [
	<generated>
	'BLSouthAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLSouthAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLSouthAlignement class >> requirements [

	<generated>
	^ {  }
]
