Class {
	#name : #BLSouthEastAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLSouthEastAlignement class >> annotation [

	<MSEClass: #SouthEastAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLSouthEastAlignement class >> generatedSlotNames [
	<generated>
	'BLSouthEastAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLSouthEastAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLSouthEastAlignement class >> requirements [

	<generated>
	^ {  }
]
