Class {
	#name : #BLSouthWestAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLSouthWestAlignement class >> annotation [

	<MSEClass: #SouthWestAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLSouthWestAlignement class >> generatedSlotNames [
	<generated>
	'BLSouthWestAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLSouthWestAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLSouthWestAlignement class >> requirements [

	<generated>
	^ {  }
]
