Class {
	#name : #BLWestAlignement,
	#superclass : #BLAlignement,
	#category : #'BL-Model-Entities'
}

{ #category : #meta }
BLWestAlignement class >> annotation [

	<MSEClass: #WestAlignement super: #BLAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLWestAlignement class >> generatedSlotNames [
	<generated>
	'BLWestAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLWestAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLWestAlignement class >> requirements [

	<generated>
	^ {  }
]
