Extension { #name : #CSNLAlignement }

{ #category : #'*Casino-Model-Layout-Extension' }
CSNLAlignement >> isCenter [
	^ false
]

{ #category : #'*Casino-Model-Layout-Extension' }
CSNLAlignement >> isEast [
	^ false
]

{ #category : #'*Casino-Model-Layout-Extension' }
CSNLAlignement >> isMiddle [
	^ false
]

{ #category : #'*Casino-Model-Layout-Extension' }
CSNLAlignement >> isNorth [
	^ false
]

{ #category : #'*Casino-Model-Layout-Extension' }
CSNLAlignement >> isSouth [
	^ false
]

{ #category : #'*Casino-Model-Layout-Extension' }
CSNLAlignement >> isWest [
	^ false
]
