Class {
	#name : #BLAlignementCreationTest,
	#superclass : #TestCase,
	#category : #'BL-Model-CoreWeb-Importer-Tests'
}

{ #category : #tests }
BLAlignementCreationTest >> testCenter [
]

{ #category : #tests }
BLAlignementCreationTest >> testEast [
]

{ #category : #tests }
BLAlignementCreationTest >> testNorth [
]

{ #category : #tests }
BLAlignementCreationTest >> testNorthEast [
]

{ #category : #tests }
BLAlignementCreationTest >> testNorthWes [
]

{ #category : #tests }
BLAlignementCreationTest >> testSouth [
]

{ #category : #tests }
BLAlignementCreationTest >> testSouthEast [
]

{ #category : #tests }
BLAlignementCreationTest >> testSouthWest [
]

{ #category : #tests }
BLAlignementCreationTest >> testWest [
]
