Class {
	#name : #BLGActionAttribute,
	#superclass : #BLGAttribute,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGActionAttribute class >> annotation [

	<generated>
	<MSEClass: #ActionAttribute super: #BLGAttribute>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGActionAttribute class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGActionAttribute class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGActionAttribute class >> requirements [

	<generated>
	^ {  }
]
