Class {
	#name : #BLGAttribute,
	#superclass : #BLGOriginedEntity,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGAttribute class >> annotation [

	<generated>
	<MSEClass: #Attribute super: #BLGOriginedEntity>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGAttribute class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGAttribute class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGAttribute class >> requirements [

	<generated>
	^ {  }
]
