Class {
	#name : #BLGBehavior,
	#superclass : #BLGOriginedEntity,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGBehavior class >> annotation [

	<generated>
	<MSEClass: #Behavior super: #BLGOriginedEntity>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGBehavior class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGBehavior class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGBehavior class >> requirements [

	<generated>
	^ {  }
]
