Class {
	#name : #BLGOriginedEntity,
	#superclass : #MooseEntity,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGOriginedEntity class >> annotation [

	<generated>
	<MSEClass: #OriginedEntity super: #MooseEntity>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGOriginedEntity class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGOriginedEntity class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGOriginedEntity class >> requirements [

	<generated>
	^ {  }
]
