Class {
	#name : #BLGPhase,
	#superclass : #BLGOriginedEntity,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGPhase class >> annotation [

	<generated>
	<MSEClass: #Phase super: #BLGOriginedEntity>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGPhase class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGPhase class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGPhase class >> requirements [

	<generated>
	^ {  }
]
