Class {
	#name : #BLGPageMetier,
	#superclass : #BLGUIContainer,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGPageMetier class >> annotation [

	<generated>
	<MSEClass: #PageMetier super: #BLGUIContainer>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGPageMetier class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGPageMetier class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGPageMetier class >> requirements [

	<generated>
	^ {  }
]
