Class {
	#name : #BLGService,
	#superclass : #BLGOriginedEntity,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGService class >> annotation [

	<generated>
	<MSEClass: #Service super: #BLGOriginedEntity>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGService class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGService class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGService class >> requirements [

	<generated>
	^ {  }
]
