Class {
	#name : #BLGServiceAction,
	#superclass : #BLGBehavior,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGServiceAction class >> annotation [

	<generated>
	<MSEClass: #ServiceAction super: #BLGBehavior>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGServiceAction class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGServiceAction class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGServiceAction class >> requirements [

	<generated>
	^ {  }
]
