Class {
	#name : #BLGUILeaf,
	#superclass : #BLGWidget,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGUILeaf class >> annotation [

	<generated>
	<MSEClass: #UILeaf super: #BLGWidget>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGUILeaf class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGUILeaf class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGUILeaf class >> requirements [

	<generated>
	^ {  }
]
