Class {
	#name : #BLGUIContainer,
	#superclass : #BLGWidget,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGUIContainer class >> annotation [

	<generated>
	<MSEClass: #UIContainer super: #BLGWidget>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGUIContainer class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGUIContainer class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGUIContainer class >> requirements [

	<generated>
	^ {  }
]
