Class {
	#name : #BLGWidget,
	#superclass : #BLGOriginedEntity,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGWidget class >> annotation [

	<generated>
	<MSEClass: #Widget super: #BLGOriginedEntity>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGWidget class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGWidget class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGWidget class >> requirements [

	<generated>
	^ {  }
]
