@startuml
| UI |
start
:mooseModel]
fork
    fork 
        :generatePage;
        :uiModelPage]
    fork again
        :generateBusinessPage;
        :uiModelBusinessPage]
    fork end
:addLinksXMLUIPage;
:addLinkForAbstractTabPhase;
:linkPageBusinessPage;
:linkBusinessPageBusinessPage;
fork again
    :generateWidget;
    :addLinkXmlUIWiget;
    :uiModelWidget]
    fork
        :addLinkWidgets;
        :uiModelLinkedWidgets]
    fork again
        :generateActionAppel;
    fork again
        :addGenericAttributeToWidget;
    fork again
        :addOnClickAttribute;
    fork again
        :addDefaultAttribute;
    end fork
fork again
    :generateService;
    :generateServiceAction;
    :uiWithServices]
end fork
:modelWithFullInformationOfUI]
:linkPagesWidgets;
:addListToModel;
stop
@enduml
