Class {
	#name : #CSNModelPluginExporterAngular,
	#superclass : #CSNModelPluginExporter,
	#category : #'Casino-Model-Exporter-Angular'
}

{ #category : #printing }
CSNModelPluginExporterAngular >> printAdditionalMethodsFor: aBLPageMetier using: aCSNExporter [

	self subclassResponsibility
]

{ #category : #printing }
CSNModelPluginExporterAngular >> printConstructorVariable: aBLPageMetier using: aCSNExporter [

	self subclassResponsibility
]

{ #category : #printing }
CSNModelPluginExporterAngular >> printImportOf: aBLPageMetier using: aCSNExporter [

	self subclassResponsibility
]

{ #category : #printing }
CSNModelPluginExporterAngular >> printTSVariablesForComponent: aBLPageMetier using: aCSNExporter [

	self subclassResponsibility
]
