Class {
	#name : #CSNELCWBLTabComponent,
	#superclass : #CoreWebBLComponent,
	#category : #'Casino-CoreWeb-ExternalLibrary'
}

{ #category : #accessing }
CSNELCWBLTabComponent >> getSelector [
	^ 'bl-tab'
]

{ #category : #accessing }
CSNELCWBLTabComponent >> moduleName [
	^ 'TabComponent'
]

{ #category : #accessing }
CSNELCWBLTabComponent >> subModulePath [
	^ '/components/tab/tab/tab.component'
]
