Class {
	#name : #CSNELCWBLTabComponent,
	#superclass : #CoreWebBLComponent,
	#category : #'Casino-CoreWeb-ExternalLibrary'
}

{ #category : #accessing }
CSNELCWBLTabComponent class >> getSelector [
	^ 'bl-tab'
]

{ #category : #accessing }
CSNELCWBLTabComponent class >> moduleName [
	^ 'TabComponent'
]

{ #category : #'as yet unclassified' }
CSNELCWBLTabComponent class >> subModulePath [
	^ 'tab/tab/tab.component'
]
