Class {
	#name : #CSNELCWBLListAndDetailsComponent,
	#superclass : #CoreWebBLComponent,
	#category : #'Casino-CoreWeb-ExternalLibrary'
}

{ #category : #accessing }
CSNELCWBLListAndDetailsComponent class >> getSelector [
	^ 'bl-liste-et-details'
]

{ #category : #accessing }
CSNELCWBLListAndDetailsComponent class >> moduleName [
	^ 'ListeEtDetailsComponent'
]

{ #category : #accessing }
CSNELCWBLListAndDetailsComponent class >> subModulePath [
	^ 'liste-et-details/liste-et-details.component'
]
