Class {
	#name : #CSNELCWBLListAndDetailsComponent,
	#superclass : #CoreWebBLComponent,
	#category : #'Casino-CoreWeb-ExternalLibrary'
}

{ #category : #accessing }
CSNELCWBLListAndDetailsComponent class >> getSelector [
	^ 'bl-table'
]

{ #category : #accessing }
CSNELCWBLListAndDetailsComponent class >> moduleName [
	^ 'BlTableComponent'
]

{ #category : #accessing }
CSNELCWBLListAndDetailsComponent class >> subModulePath [
	^ 'table/table.component'
]
