Class {
	#name : #CSNELCWBLSimpleLinkComponent,
	#superclass : #CoreWebBLComponent,
	#category : #'Casino-CoreWeb-ExternalLibrary'
}

{ #category : #'as yet unclassified' }
CSNELCWBLSimpleLinkComponent class >> getSelector [
	^ 'bl-simple-link'
]

{ #category : #accessing }
CSNELCWBLSimpleLinkComponent class >> moduleName [
	^ 'BlSimpleLinkComponent'
]

{ #category : #'as yet unclassified' }
CSNELCWBLSimpleLinkComponent class >> subModulePath [
	^ 'link-button/simple-link/simple-link.component'
]
