Class {
	#name : #CSNBSourceTextAnchor,
	#superclass : #MooseEntity,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBSourceTextAnchor class >> annotation [

	<MSEClass: #SourceTextAnchor super: #MooseEntity>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBSourceTextAnchor class >> generatedSlotNames [
	<generated>
	'CSNBSourceTextAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBSourceTextAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBSourceTextAnchor class >> metamodel [

	<generated>
	^ (self class environment at: #CSNBehaviorModelGenerator) metamodel
]

{ #category : #meta }
CSNBSourceTextAnchor class >> requirements [

	<generated>
	^ {  }
]

{ #category : #testing }
CSNBSourceTextAnchor >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isAttribute [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isClass [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isFunction [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isInheritance [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isMethod [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isNamespace [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isPackage [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isReference [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceTextAnchor >> isType [

	<generated>
	^ false
]
