"
I represent a call which will create a dialog with the data as inside it (it corresponds most of the time to a String, but it can change)
"
Class {
	#name : #CSNBOpenDialog,
	#superclass : #FASTExpression,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBOpenDialog class >> annotation [

	<FMClass: #OpenDialog super: #FASTExpression>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]
