"
A boolean literal
"
Class {
	#name : #CSNBBooleanLiteral,
	#superclass : #CSNBLiteral,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBBooleanLiteral class >> annotation [

	<MSEClass: #BooleanLiteral super: #CSNBLiteral>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBBooleanLiteral class >> generatedSlotNames [
	<generated>
	'CSNBBooleanLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBBooleanLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBBooleanLiteral class >> requirements [

	<generated>
	^ {  }
]
