"
A string literal
"
Class {
	#name : #CSNBStringLiteral,
	#superclass : #CSNBLiteral,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBStringLiteral class >> annotation [

	<MSEClass: #StringLiteral super: #CSNBLiteral>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBStringLiteral class >> generatedSlotNames [
	<generated>
	'CSNBStringLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBStringLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBStringLiteral class >> requirements [

	<generated>
	^ {  }
]
