Class {
	#name : #CSNBModel,
	#superclass : #MooseModel,
	#category : #'Casino-Behavior-Model-Model'
}

{ #category : #accessing }
CSNBModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'FAST-Java-Model' #'FAST-Core-Model' 'Casino-Model-UI-SubEntities' 'Casino-Model-Layout' 'Casino-Model-CoreWeb' #'Casino-Model')
]

{ #category : #meta }
CSNBModel class >> annotation [
	<FMClass: #CSNBModel super: #MooseModel>
	<package: #'Casino-Behavior-Model'>
	<generated>
]
