"
An undefined object literal
"
Class {
	#name : #CSNBNullPointerLiteral,
	#superclass : #CSNBLiteral,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBNullPointerLiteral class >> annotation [

	<MSEClass: #NullPointerLiteral super: #CSNBLiteral>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBNullPointerLiteral class >> generatedSlotNames [
	<generated>
	'CSNBNullPointerLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBNullPointerLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBNullPointerLiteral class >> requirements [

	<generated>
	^ {  }
]
