"
A node of a statement which is representing a single expression. 
"
Class {
	#name : #CSNBExpressionStatement,
	#superclass : #CSNBStatement,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBExpressionStatement class >> annotation [

	<MSEClass: #ExpressionStatement super: #CSNBStatement>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBExpressionStatement class >> generatedSlotNames [
	<generated>
	'CSNBExpressionStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBExpressionStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBExpressionStatement class >> requirements [

	<generated>
	^ {  }
]
