"
I represent an Synchrone call (normal call) to a distant service
"
Class {
	#name : #CSNBSynchroneCall,
	#superclass : #CSNBCall,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBSynchroneCall class >> annotation [

	<MSEClass: #SynchroneCall super: #CSNBCall>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBSynchroneCall class >> generatedSlotNames [
	<generated>
	'CSNBSynchroneCall class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBSynchroneCall class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBSynchroneCall class >> requirements [

	<generated>
	^ {  }
]
