"
A character literal
"
Class {
	#name : #CSNBCharacterLiteral,
	#superclass : #CSNBLiteral,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBCharacterLiteral class >> annotation [

	<MSEClass: #CharacterLiteral super: #CSNBLiteral>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBCharacterLiteral class >> generatedSlotNames [
	<generated>
	'CSNBCharacterLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBCharacterLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBCharacterLiteral class >> requirements [

	<generated>
	^ {  }
]
