Class {
	#name : #CSNBSourceAnchor,
	#superclass : #MooseEntity,
	#category : #'Casino-Behavior-Model-Entities'
}

{ #category : #meta }
CSNBSourceAnchor class >> annotation [

	<MSEClass: #SourceAnchor super: #MooseEntity>
	<package: #'Casino-Behavior-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNBSourceAnchor class >> generatedSlotNames [
	<generated>
	'CSNBSourceAnchor class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNBSourceAnchor class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNBSourceAnchor class >> metamodel [

	<generated>
	^ (self class environment at: #CSNBehaviorModelGenerator) metamodel
]

{ #category : #meta }
CSNBSourceAnchor class >> requirements [

	<generated>
	^ {  }
]

{ #category : #testing }
CSNBSourceAnchor >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isAttribute [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isClass [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isFunction [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isInheritance [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isMethod [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isNamespace [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isPackage [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isReference [

	<generated>
	^ false
]

{ #category : #testing }
CSNBSourceAnchor >> isType [

	<generated>
	^ false
]
