Class {
	#name : #CSNLModel,
	#superclass : #MooseModel,
	#category : #'Casino-Model-Layout'
}

{ #category : #accessing }
CSNLModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'Casino-Model')
]

{ #category : #meta }
CSNLModel class >> annotation [
	<FMClass: #CSNLModel super: #MooseModel>
	<package: #'Casino-Model-Layout'>
	<generated>
]
