Class {
	#name : #BLNormalAttribute,
	#superclass : #BLAttribute,
	#category : 'BL-Model-Entities'
}

{ #category : #meta }
BLNormalAttribute class >> annotation [

	<generated>
	<MSEClass: #NormalAttribute super: #BLAttribute>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLNormalAttribute class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLNormalAttribute class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLNormalAttribute class >> requirements [

	<generated>
	^ {  }
]
