Class {
	#name : #BLVariableAttribute,
	#superclass : #BLAttribute,
	#category : 'BL-Model-Entities'
}

{ #category : #meta }
BLVariableAttribute class >> annotation [

	<generated>
	<MSEClass: #VariableAttribute super: #BLAttribute>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
BLVariableAttribute class >> generatedSlotNames [
	<generated>
	'BLVariableAttribute class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
BLVariableAttribute class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLVariableAttribute class >> requirements [

	<generated>
	^ {  }
]
