Class {
	#name : #CSNAbsoluteSize,
	#superclass : #CSNSize,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNAbsoluteSize class >> annotation [

	<MSEClass: #AbsoluteSize super: #CSNSize>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNAbsoluteSize class >> generatedSlotNames [
	<generated>
	'CSNAbsoluteSize class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNAbsoluteSize class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNAbsoluteSize class >> requirements [

	<generated>
	^ {  }
]
