Class {
	#name : #CSNAbsolutePosition,
	#superclass : #CSNPosition,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNAbsolutePosition class >> annotation [

	<MSEClass: #AbsolutePosition super: #CSNPosition>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNAbsolutePosition class >> generatedSlotNames [
	<generated>
	'CSNAbsolutePosition class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNAbsolutePosition class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNAbsolutePosition class >> requirements [

	<generated>
	^ {  }
]
