Class {
	#name : #CSNCenterAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNCenterAlignement class >> annotation [

	<MSEClass: #CenterAlignement super: #CSNAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNCenterAlignement class >> generatedSlotNames [
	<generated>
	'BLCenterAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNCenterAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNCenterAlignement class >> requirements [

	<generated>
	^ {  }
]
