Class {
	#name : #CSNEastAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNEastAlignement class >> annotation [

	<MSEClass: #EastAlignement super: #CSNAlignement>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNEastAlignement class >> generatedSlotNames [
	<generated>
	'BLEastAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNEastAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNEastAlignement class >> requirements [

	<generated>
	^ {  }
]
