Class {
	#name : #CSNNorthEastAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNNorthEastAlignement class >> annotation [

	<MSEClass: #NorthEastAlignement super: #CSNAlignement>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNNorthEastAlignement class >> generatedSlotNames [
	<generated>
	'CSNNorthEastAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNNorthEastAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNNorthEastAlignement class >> requirements [

	<generated>
	^ {  }
]
