Class {
	#name : #CSNNorthAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNNorthAlignement class >> annotation [

	<MSEClass: #NorthAlignement super: #CSNAlignement>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNNorthAlignement class >> generatedSlotNames [
	<generated>
	'CSNNorthAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNNorthAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNNorthAlignement class >> requirements [

	<generated>
	^ {  }
]
