Class {
	#name : #CSNNorthWestAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNNorthWestAlignement class >> annotation [

	<MSEClass: #NorthWestAlignement super: #CSNAlignement>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNNorthWestAlignement class >> generatedSlotNames [
	<generated>
	'CSNNorthWestAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNNorthWestAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNNorthWestAlignement class >> requirements [

	<generated>
	^ {  }
]
