Class {
	#name : #CSNRelativePosition,
	#superclass : #CSNPosition,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNRelativePosition class >> annotation [

	<MSEClass: #RelativePosition super: #CSNPosition>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNRelativePosition class >> generatedSlotNames [
	<generated>
	'CSNRelativePosition class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNRelativePosition class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNRelativePosition class >> requirements [

	<generated>
	^ {  }
]
