Class {
	#name : #CSNRelativeSize,
	#superclass : #CSNSize,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNRelativeSize class >> annotation [

	<MSEClass: #RelativeSize super: #CSNSize>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNRelativeSize class >> generatedSlotNames [
	<generated>
	'BLRelativeSize class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNRelativeSize class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNRelativeSize class >> requirements [

	<generated>
	^ {  }
]
