Class {
	#name : #CSNSouthWestAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNSouthWestAlignement class >> annotation [

	<MSEClass: #SouthWestAlignement super: #CSNAlignement>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNSouthWestAlignement class >> generatedSlotNames [
	<generated>
	'CSNSouthWestAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNSouthWestAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNSouthWestAlignement class >> requirements [

	<generated>
	^ {  }
]
