Class {
	#name : #CSNSouthEastAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNSouthEastAlignement class >> annotation [

	<MSEClass: #SouthEastAlignement super: #CSNAlignement>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNSouthEastAlignement class >> generatedSlotNames [
	<generated>
	'CSNSouthEastAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNSouthEastAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNSouthEastAlignement class >> requirements [

	<generated>
	^ {  }
]
