Class {
	#name : #CSNSouthAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNSouthAlignement class >> annotation [

	<MSEClass: #SouthAlignement super: #CSNAlignement>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNSouthAlignement class >> generatedSlotNames [
	<generated>
	'CSNSouthAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNSouthAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNSouthAlignement class >> requirements [

	<generated>
	^ {  }
]
