"
I will be removed soon
"
Class {
	#name : #CSNVariableAttribute,
	#superclass : #CSNAttribute,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNVariableAttribute class >> annotation [

	<MSEClass: #VariableAttribute super: #CSNAttribute>
	<package: #'BL-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNVariableAttribute class >> generatedSlotNames [
	<generated>
	'BLVariableAttribute class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNVariableAttribute class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNVariableAttribute class >> requirements [

	<generated>
	^ {  }
]
