Class {
	#name : #CSNWestAlignement,
	#superclass : #CSNAlignement,
	#category : #'Casino-Model-Entities'
}

{ #category : #meta }
CSNWestAlignement class >> annotation [

	<MSEClass: #WestAlignement super: #CSNAlignement>
	<package: #'Casino-Model'>
	<generated>
	^self
]

{ #category : #generator }
CSNWestAlignement class >> generatedSlotNames [
	<generated>
	'CSNWestAlignement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
CSNWestAlignement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
CSNWestAlignement class >> requirements [

	<generated>
	^ {  }
]
