Class {
	#name : #CSNBuModel,
	#superclass : #MooseModel,
	#category : #'Casino-Business-Model-Model'
}

{ #category : #accessing }
CSNBuModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits' #'Casino-Model')
]

{ #category : #meta }
CSNBuModel class >> annotation [
	<FMClass: #CSNBuModel super: #MooseModel>
	<package: #'Casino-Business-Model'>
	<generated>
]
