Class {
	#name : #BLActionGenerated,
	#superclass : #MooseEntity,
	#category : 'BLMetamodel-Generated-Entities'
}

{ #category : #meta }
BLActionGenerated class >> annotation [

	<MSEClass: #Action super: #MooseEntity>
	<package: #'BLMetamodel-Generated'>
	^self
]

{ #category : #meta }
BLActionGenerated class >> metamodel [

	^ BLMetamodelGenerator metamodel
]

{ #category : #meta }
BLActionGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
BLActionGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
