Class {
	#name : #BLactionAsynchroneGenerated,
	#superclass : #BLActionGenerated,
	#category : 'BLMetamodel-Generated-Entities'
}

{ #category : #meta }
BLactionAsynchroneGenerated class >> annotation [

	<MSEClass: #actionAsynchrone super: #BLActionGenerated>
	<package: #'BLMetamodel-Generated'>
	^self
]

{ #category : #meta }
BLactionAsynchroneGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
BLactionAsynchroneGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
