Class {
	#name : #BLactionAppelGenerated,
	#superclass : #BLActionGenerated,
	#category : 'BLMetamodel-Generated-Entities'
}

{ #category : #meta }
BLactionAppelGenerated class >> annotation [

	<MSEClass: #actionAppel super: #BLActionGenerated>
	<package: #'BLMetamodel-Generated'>
	^self
]

{ #category : #meta }
BLactionAppelGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
BLactionAppelGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
