Class {
	#name : #BLImportingContext,
	#superclass : #FamixImportingContext,
	#category : 'BLMetamodel-Generated'
}

{ #category : #testing }
BLImportingContext >> importAction [

	^ self import: BLAction
]

{ #category : #testing }
BLImportingContext >> importPageMetier [

	^ self import: BLPageMetier
]

{ #category : #testing }
BLImportingContext >> importPhase [

	^ self import: BLPhase
]

{ #category : #testing }
BLImportingContext >> importPhaseNotStandalone [

	^ self import: BLPhaseNotStandalone
]

{ #category : #testing }
BLImportingContext >> importPhaseStandAlone [

	^ self import: BLPhaseStandAlone
]

{ #category : #testing }
BLImportingContext >> importService [

	^ self import: BLService
]

{ #category : #testing }
BLImportingContext >> importWidget [

	^ self import: BLWidget
]

{ #category : #testing }
BLImportingContext >> importactionAppel [

	^ self import: BLactionAppel
]

{ #category : #testing }
BLImportingContext >> importactionAsynchrone [

	^ self import: BLactionAsynchrone
]

{ #category : #testing }
BLImportingContext >> shouldImportAction [

	^ self shouldImport: BLAction
]

{ #category : #testing }
BLImportingContext >> shouldImportPageMetier [

	^ self shouldImport: BLPageMetier
]

{ #category : #testing }
BLImportingContext >> shouldImportPhase [

	^ self shouldImport: BLPhase
]

{ #category : #testing }
BLImportingContext >> shouldImportPhaseNotStandalone [

	^ self shouldImport: BLPhaseNotStandalone
]

{ #category : #testing }
BLImportingContext >> shouldImportPhaseStandAlone [

	^ self shouldImport: BLPhaseStandAlone
]

{ #category : #testing }
BLImportingContext >> shouldImportService [

	^ self shouldImport: BLService
]

{ #category : #testing }
BLImportingContext >> shouldImportWidget [

	^ self shouldImport: BLWidget
]

{ #category : #testing }
BLImportingContext >> shouldImportactionAppel [

	^ self shouldImport: BLactionAppel
]

{ #category : #testing }
BLImportingContext >> shouldImportactionAsynchrone [

	^ self shouldImport: BLactionAsynchrone
]
