Class {
	#name : #BLPhaseNotStandaloneGenerated,
	#superclass : #BLPhaseGenerated,
	#category : 'BLMetamodel-Generated-Entities'
}

{ #category : #meta }
BLPhaseNotStandaloneGenerated class >> annotation [

	<MSEClass: #PhaseNotStandalone super: #BLPhaseGenerated>
	<package: #'BLMetamodel-Generated'>
	^self
]

{ #category : #meta }
BLPhaseNotStandaloneGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
BLPhaseNotStandaloneGenerated class >> statefulTraits [

	<statefulTraits>
	^ {BLTWithPageMetiers}
]
