Class {
	#name : #BLPhaseStandAloneGenerated,
	#superclass : #BLPhaseGenerated,
	#category : 'BLMetamodel-Generated-Entities'
}

{ #category : #meta }
BLPhaseStandAloneGenerated class >> annotation [

	<MSEClass: #PhaseStandAlone super: #BLPhaseGenerated>
	<package: #'BLMetamodel-Generated'>
	^self
]

{ #category : #meta }
BLPhaseStandAloneGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
BLPhaseStandAloneGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
