Class {
	#name : #BLServiceGenerated,
	#superclass : #MooseEntity,
	#category : 'BLMetamodel-Generated-Entities'
}

{ #category : #meta }
BLServiceGenerated class >> annotation [

	<MSEClass: #Service super: #MooseEntity>
	<package: #'BLMetamodel-Generated'>
	^self
]

{ #category : #meta }
BLServiceGenerated class >> metamodel [

	^ BLMetamodelGenerator metamodel
]

{ #category : #meta }
BLServiceGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
BLServiceGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
