Class {
	#name : #BLWidgetGenerated,
	#superclass : #MooseEntity,
	#category : 'BLMetamodel-Generated-Entities'
}

{ #category : #meta }
BLWidgetGenerated class >> annotation [

	<MSEClass: #Widget super: #MooseEntity>
	<package: #'BLMetamodel-Generated'>
	^self
]

{ #category : #meta }
BLWidgetGenerated class >> metamodel [

	^ BLMetamodelGenerator metamodel
]

{ #category : #meta }
BLWidgetGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
BLWidgetGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
