Extension { #name : #CSNModelVisitor }

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWAutoComplete: aCSNUICWAutoComplete [
	<generated>
	^ self visitCSNUIInput: aCSNUICWAutoComplete
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWAutoComplete: aCSNUICWAutoComplete [
	<generated>
	^ self visitCSNUIInput: aCSNUICWAutoComplete
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWChart: aCSNUICWChart [
	<generated>
	^ self visitCSNContainer: aCSNUICWChart
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWChart: aCSNUICWChart [
	<generated>
	^ self visitCSNContainer: aCSNUICWChart
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWClickHandler: aCSNUICWClickHandler [
	<generated>
	^ self visitCSNAction: aCSNUICWClickHandler
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWClickHandler: aCSNUICWClickHandler [
	<generated>
	^ self visitCSNAction: aCSNUICWClickHandler
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWCoreCellWidth: aCSNUICWCoreCellWidth [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreCellWidth
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWCoreCellWidth: aCSNUICWCoreCellWidth [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreCellWidth
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWCoreColSpan: aCSNUICWCoreColSpan [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreColSpan
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWCoreColSpan: aCSNUICWCoreColSpan [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreColSpan
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWCoreHorizontalAlignement: aCSNUICWCoreHorizontalAlignement [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreHorizontalAlignement
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWCoreHorizontalAlignement: aCSNUICWCoreHorizontalAlignement [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreHorizontalAlignement
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWCoreRowSpan: aCSNUICWCoreRowSpan [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreRowSpan
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWCoreRowSpan: aCSNUICWCoreRowSpan [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreRowSpan
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWCoreVerticalAlignement: aCSNUICWCoreVerticalAlignement [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreVerticalAlignement
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWCoreVerticalAlignement: aCSNUICWCoreVerticalAlignement [
	<generated>
	^ self visitCSNAttribute: aCSNUICWCoreVerticalAlignement
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWDialog: aCSNUICWDialog [
	<generated>
	^ self visitCSNContainer: aCSNUICWDialog
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWDialog: aCSNUICWDialog [
	<generated>
	^ self visitCSNContainer: aCSNUICWDialog
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWDynamicFieldset: aCSNUICWDynamicFieldset [
	<generated>
	^ self visitCSNAttribute: aCSNUICWDynamicFieldset
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWDynamicFieldset: aCSNUICWDynamicFieldset [
	<generated>
	^ self visitCSNAttribute: aCSNUICWDynamicFieldset
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWExtendedLink: aCSNUICWExtendedLink [
	<generated>
	^ self visitCSNUILink: aCSNUICWExtendedLink
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWExtendedLink: aCSNUICWExtendedLink [
	^ self visitCSNUILink: aCSNUICWExtendedLink
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWFileUploadPanel: aCSNUICWFileUploadPanel [
	^ self visitCSNContainer: aCSNUICWFileUploadPanel
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWFileUploadPanel: aCSNUICWFileUploadPanel [
	^ self visitCSNContainer: aCSNUICWFileUploadPanel
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWGroupFieldset: aCSNUICWGroupFieldset [
	<generated>
	^ self visitCSNAttribute: aCSNUICWGroupFieldset
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWGroupFieldset: aCSNUICWGroupFieldset [
	<generated>
	^ self visitCSNAttribute: aCSNUICWGroupFieldset
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWHTML: aCSNUICWHTML [
	^ self visitCSNContainer: aCSNUICWHTML
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWHTML: aCSNUICWHTML [
	<generated>
	^ self visitCSNContainer: aCSNUICWHTML
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWLightFieldset: aCSNUICWLightFieldset [
	<generated>
	^ self visitCSNAttribute: aCSNUICWLightFieldset
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWLightFieldset: aCSNUICWLightFieldset [
	<generated>
	^ self visitCSNAttribute: aCSNUICWLightFieldset
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWLinkSimple: aCSNUICWLinkSimple [
	^ self visitCSNContainer: aCSNUICWLinkSimple
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWLinkSimple: aCSNUICWLinkSimple [
	^ self visitCSNContainer: aCSNUICWLinkSimple
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWListAndDetails: aCSNUICWListAndDetails [
	^ self visitCSNContainer: aCSNUICWListAndDetails
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWListAndDetails: aCSNUICWListAndDetails [
	^ self visitCSNContainer: aCSNUICWListAndDetails
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWMultiCombo: aCSNUICWMultiCombo [
	^ self visitCSNContainer: aCSNUICWMultiCombo
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWMultiCombo: aCSNUICWMultiCombo [
	^ self visitCSNContainer: aCSNUICWMultiCombo
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWOpen: aCSNUICWOpen [
	<generated>
	^ self visitCSNAttribute: aCSNUICWOpen
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWOpen: aCSNUICWOpen [
	<generated>
	^ self visitCSNAttribute: aCSNUICWOpen
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWProgressBar: aCSNUICWProgressBar [
	<generated>
	^ self visitCSNContainer: aCSNUICWProgressBar
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWProgressBar: aCSNUICWProgressBar [
	<generated>
	^ self visitCSNContainer: aCSNUICWProgressBar
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWRechercheEtListe: aCSNUICWRechercheEtListe [
	^ self visitCSNContainer: aCSNUICWRechercheEtListe
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWRechercheEtListe: aCSNUICWRechercheEtListe [
	^ self visitCSNContainer: aCSNUICWRechercheEtListe
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWRichTextArea: aCSNUICWRichTextArea [
	<generated>
	^ self visitCSNUIInput: aCSNUICWRichTextArea
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWRichTextArea: aCSNUICWRichTextArea [
	<generated>
	^ self visitCSNUIInput: aCSNUICWRichTextArea
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWSplitButton: aCSNUICWSplitButton [
	<generated>
	^ self visitCSNUIInput: aCSNUICWSplitButton
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWSplitButton: aCSNUICWSplitButton [
	<generated>
	^ self visitCSNUIInput: aCSNUICWSplitButton
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor >> visitCSNUICWSwitch: aCSNUICWSwitch [
	<generated>
	^ self visitCSNUIInput: aCSNUICWSwitch
]

{ #category : #'*Casino-Model-CoreWeb-Visitor' }
CSNModelVisitor class >> visitCSNUICWSwitch: aCSNUICWSwitch [
	<generated>
	^ self visitCSNUIInput: aCSNUICWSwitch
]
