Extension { #name : #CSNLSouthWestAlignement }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLSouthWestAlignement classSide >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLSouthWestAlignement: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLSouthWestAlignement >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLSouthWestAlignement: self
]
