Extension { #name : #CSNLSouthEastAlignement }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLSouthEastAlignement class >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLSouthEastAlignement: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLSouthEastAlignement >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLSouthEastAlignement: self
]
