Extension { #name : #CSNLNorthEastAlignement }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLNorthEastAlignement class >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLNorthEastAlignement: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLNorthEastAlignement >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLNorthEastAlignement: self
]
