Extension { #name : #CSNLNorthWestAlignement }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLNorthWestAlignement class >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLNorthWestAlignement: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNLNorthWestAlignement >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNLNorthWestAlignement: self
]
