Extension { #name : #CSNUICWDynamicFieldset }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUICWDynamicFieldset >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUICWDynamicFieldset: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUICWDynamicFieldset class >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUICWDynamicFieldset: self
]
