Extension { #name : #CSNUICWCoreHorizontalAlignement }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUICWCoreHorizontalAlignement classSide >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUICWCoreHorizontalAlignement: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUICWCoreHorizontalAlignement >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUICWCoreHorizontalAlignement: self
]
