Extension { #name : #CSNUICWCoreVerticalAlignement }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUICWCoreVerticalAlignement >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUICWCoreVerticalAlignement: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUICWCoreVerticalAlignement classSide >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUICWCoreVerticalAlignement: self
]
