Extension { #name : #CSNUIInputDatetimeLocal }

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUIInputDatetimeLocal class >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUIInputDatetimeLocal: self
]

{ #category : #'*Casino-Model-Visitor-generated' }
CSNUIInputDatetimeLocal >> accept: aCSNModelVisitor [
	<generated>
	^ aCSNModelVisitor visitCSNUIInputDatetimeLocal: self
]
