"
Images in HTML have a set of size attributes, which specifies the width and height of an image (or div element)
"
Class {
	#name : #CSNUIHeight,
	#superclass : #CSNAttribute,
	#instVars : [
		'text'
	],
	#category : #'Casino-Model-UI-SubEntities-Attributes'
}

{ #category : #meta }
CSNUIHeight class >> annotation [

	<MSEClass: #Height super: #CSNAttribute>
	<package: #'Casino-Model-UI-SubEntities'>
	<generated>
	^self
]
