"
Can be only contained by a BLUITabManager

contain the title of the tag 
an optionnal icon
the model -> contained widget 
"
Class {
	#name : #CSNUITab,
	#superclass : #CSNContainer,
	#category : #'Casino-Model-UI-SubEntities-Widgets-Extended'
}

{ #category : #meta }
CSNUITab class >> annotation [

	<FMClass: #Tab super: #CSNContainer>
	<package: #'Casino-Model-UI-SubEntities'>
	<generated>
	^self
]
