Class {
	#name : #CSNUIModel,
	#superclass : #MooseModel,
	#category : #'Casino-Model-UI-SubEntities-Model'
}

{ #category : #accessing }
CSNUIModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #('Casino-Model-Layout' #'Casino-Model')
]

{ #category : #meta }
CSNUIModel class >> annotation [
	<MSEClass: #CSNUIModel super: #MooseModel>
	<package: #'Casino-Model-UI-SubEntities'>
	<generated>
]
