"
HTML images are defined with the <img> tag.

The filename of the image source is specified in the src attribute:

Example
<img src=""img_girl.jpg"">
"
Class {
	#name : #CSNUISrc,
	#superclass : #CSNAttribute,
	#category : #'Casino-Model-UI-SubEntities-Attributes'
}

{ #category : #meta }
CSNUISrc class >> annotation [

	<MSEClass: #Src super: #CSNAttribute>
	<package: #'Casino-Model-UI-SubEntities'>
	<generated>
	^self
]
