Class {
	#name : #BLGAction,
	#superclass : #MooseEntity,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGAction class >> annotation [

	<generated>
	<MSEClass: #Action super: #MooseEntity>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGAction class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGAction class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGAction class >> requirements [

	<generated>
	^ {  }
]
