Class {
	#name : #BLGActionAppel,
	#superclass : #BLGAction,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGActionAppel class >> annotation [

	<generated>
	<MSEClass: #ActionAppel super: #BLGAction>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGActionAppel class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGActionAppel class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGActionAppel class >> requirements [

	<generated>
	^ {  }
]
