Class {
	#name : #BLGNormalAttribute,
	#superclass : #BLGAttribute,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGNormalAttribute class >> annotation [

	<generated>
	<MSEClass: #NormalAttribute super: #BLGAttribute>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGNormalAttribute class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGNormalAttribute class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGNormalAttribute class >> requirements [

	<generated>
	^ {  }
]
