Class {
	#name : #BLGVariableAttribute,
	#superclass : #BLGAttribute,
	#category : 'BL-Model-Generated-Entities'
}

{ #category : #meta }
BLGVariableAttribute class >> annotation [

	<generated>
	<MSEClass: #VariableAttribute super: #BLGAttribute>
	<package: #'BL-Model-Generated'>
	<generated>
	^self
]

{ #category : #generator }
BLGVariableAttribute class >> generatedSlotNames [
	<generated>
	^ #()
]

{ #category : #generator }
BLGVariableAttribute class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
BLGVariableAttribute class >> requirements [

	<generated>
	^ {  }
]
