# This is a basic workflow to help you get started with Actions

name: CI Moose11

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  push:
    branches: 
      - main
      - v*
      - master
  pull_request:
    branches:    
      - main
      - v*
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: Casino
    strategy:
      matrix:
        smalltalk: [ Moose64-11 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
